services:
    long_running.doctrine_orm.clear_entity_managers:
        class: LongRunning\Plugin\DoctrineORMPlugin\ClearEntityManagers
        public: false
        arguments:
            - '@doctrine'
            - '@logger'
        tags:
            - { name: long_running.cleaner }

    long_running.doctrine_orm.reset_closed_entity_managers:
        class: LongRunning\Plugin\DoctrineORMPlugin\ResetClosedEntityManagers
        public: false
        arguments:
            - '@doctrine'
            - '@logger'
        tags:
            - { name: long_running.cleaner }
