services:
    long_running.doctrine_dbal.close_connections:
        class: LongRunning\Plugin\DoctrineDBALPlugin\CloseConnections
        public: false
        arguments:
            - @doctrine
            - @logger
        tags:
            - { name: long_running.cleaner }
