services:
    long_running.delegating_cleaner:
        class: LongRunning\Core\DelegatingCleaner
        arguments:
            # will be populated by RegisterCleanersPass
            - []

    LongRunning\Core\DelegatingCleaner:
        alias: long_running.delegating_cleaner
