services:
    long_running.swift_mailer.clear_spools:
        class: LongRunning\Plugin\SwiftMailerPlugin\ClearSpools
        public: false
        arguments:
            # will be populated by SwiftMailerPass
            - []
            - []
            - '@logger'
        tags:
            - { name: long_running.cleaner }
